**introduce NumPy**


In [3]:
import numpy as np

**Converting Python sequences to NumPy arrays**

**Conversion from other Python structures (i.e. lists and tuples)**

In [4]:
my_arr = np.array([[10,20,30,40],[50,60,70,80]],np.int16)

In [5]:
my_arr

array([[10, 20, 30, 40],
       [50, 60, 70, 80]], dtype=int16)

In [6]:
my_arr[1,2]

np.int16(70)

In [7]:
shape = my_arr.shape
Type = my_arr.dtype
print(shape,Type)

(2, 4) int16


In [8]:
my_arr[0,1] = 100

In [9]:
my_arr

array([[ 10, 100,  30,  40],
       [ 50,  60,  70,  80]], dtype=int16)

**Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)**

In [10]:
zeros = np.zeros((2,5))

In [11]:
zeros.shape

(2, 5)

In [12]:
zeros.dtype

dtype('float64')

In [13]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
Range = np.arange(10)

In [15]:
Range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
lspace = np.linspace(1,5,10)
#here 10 number betwwen 1 to 5  and this 10 number s defference is same.

In [17]:
lspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [18]:
emp = np.empty((4,6))

In [19]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.86921822e-306, 1.42413555e-306, 1.78019082e-306],
       [1.37960147e-306, 1.33511562e-306, 2.22518251e-306,
        1.33511969e-306, 1.78022342e-306, 1.05700345e-307],
       [1.69118108e-306, 8.06632139e-308, 1.20160711e-306,
        1.69119330e-306, 1.29062229e-306, 1.24610383e-306],
       [6.89804132e-307, 8.45602762e-307, 1.33511969e-306,
        1.69118787e-306, 1.29061414e-306, 1.42410974e-306]])

In [20]:
emp_like = np.empty_like(lspace)

In [21]:
emp_like

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [22]:
Indentity = np.identity(10)

In [23]:
Indentity

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [24]:
Indentity.shape

(10, 10)

In [25]:
Array = np.arange(100) 

In [26]:
Array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [27]:
Array.reshape(2,50)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [28]:
Array = Array.ravel()

In [29]:
Array.shape

(100,)

In [30]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [31]:
ar = np.array(x)

In [32]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
#axis = 0 means its row of array 
ar.sum(axis=0)

array([12, 15, 18])

In [34]:
#axis =1 means its column of array
ar.sum(axis=1)

array([ 6, 15, 24])

In [35]:
ar.T
#it means transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [36]:
ar.flat
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [37]:
ar.ndim

2

In [38]:
one = np.array([1,2,3,45,8])

In [39]:
one.argmax()


np.int64(3)

In [40]:
one.argmin()

np.int64(0)

In [41]:
one.argsort()

array([0, 1, 2, 4, 3])

In [42]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ar.reshape((9,1))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

**mathematical term**

In [56]:
 ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
ar2 = np.array([
    [9,8,7],
    [6,5,4],
    [3,2,1]
])

In [58]:
ar+ar2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [59]:
ar * ar2 

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [60]:
np.square(ar)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [61]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [63]:
np.sum(ar)

np.int64(45)

In [65]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.where(ar>5) #its type is tuple

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [67]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [68]:
np.count_nonzero(ar)

9

**numpy takes less memory size**

In [71]:
import sys

In [69]:
py_ar=[0,4,55,2]

In [70]:
np_ar = np.array(py_ar)

In [ ]:
#1 integers size,how much element of this list
sys.getsizeof(1) * len(py_ar)

112

In [ ]:
np_ar.itemsize * np_ar.size
#here numpy array size is very less

32